sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123
  alioss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    bucket-name: cheng-skytakeout
  redis:
    host: localhost
    port: 6379
    # password: 123
    database: 10
  wechat:
    appid: wx5d9bb72e2616b571
    secret: 422ff18d4213e280fbcbc1329d466623
