sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123
  alioss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    bucket-name: cheng-skytakeout
  redis:
    host: localhost
    port: 6379
    password:
    database: 10
  wechat:
    appid: wx5d9bb72e2616b571
    secret: 422ff18d4213e280fbcbc1329d466623
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: C:\software\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: C:\software\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://7e6cb10a.r18.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://7e6cb10a.r18.cpolar.top/notify/refundSuccess
  shop:
    address: 西安市碑林区西安交通大学
  baidu:
    ak: 123

